# NumPy 

NumPy (o Numpy) es una biblioteca de álgebra lineal para Python, la razón por la que es tan importante es que casi todas las bibliotecas en PyData Ecosystem confían en NumPy como uno de sus principales bloques de construcción. ¡Además, lo usaremos para generar datos para nuestros ejemplos de análisis más adelante!

Numpy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C. Para obtener más información sobre por qué querría usar matrices en lugar de listas, consulte este excelente [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).


## Usando NumPy


In [1]:
import numpy as np

Numpy tiene muchas funciones y capacidades integradas. No los cubriremos todos, sino que nos centraremos en algunos de los aspectos más importantes de Numpy: vectores, matrices y generación de números. Comencemos discutiendo las matrices.

# Numpy Arrays

Las arrays NumPy son la forma principal en que usaremos Numpy a lo largo del curso. Las arrays Numpy esencialmente vienen en dos sabores: vectores y matrices. Los vectores son arreglos estrictamente unidimensionales y las matrices son bidimensionales (pero debe tener en cuenta que una matriz aún puede tener solo una fila o una columna).

Comencemos nuestra introducción explorando cómo crear matrices NumPy.

## Creating NumPy Arrays

### From a Python List

Podemos directamente de una lista o listas de lista armar una numpy array

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### arange

Retorna valores en un intervalo

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generar un array de zeros o unos

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Retorna un espacio equidistante en un intervalo.

In [14]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Crea una matriz identidad

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Hay varias maneras de crear numeros random en arrays:

### rand
Crear un array dada una shape y popularlo con muestras random de una distribución uniforme en ``[0, 1)``.

In [17]:
np.random.rand(5,4)

array([[0.54418082, 0.26712356, 0.4324254 , 0.76711605],
       [0.90106764, 0.64232925, 0.60045986, 0.77883392],
       [0.34938811, 0.75969914, 0.51489829, 0.28464833],
       [0.65164786, 0.2689368 , 0.08747824, 0.00757389],
       [0.62482392, 0.01775171, 0.72501118, 0.77721279]])

In [18]:
np.random.rand(5,5)

array([[0.21548343, 0.85032855, 0.81922649, 0.71033202, 0.7957724 ],
       [0.80000995, 0.59319992, 0.54147173, 0.49015531, 0.21082119],
       [0.81858862, 0.52064726, 0.50124767, 0.88576455, 0.78674059],
       [0.13086437, 0.49091545, 0.84176516, 0.78637045, 0.33678387],
       [0.73396176, 0.78220936, 0.89504431, 0.40408666, 0.29190003]])

### randn

Retorna muestras de una distribución normal ( "standard normal" distribution):

In [19]:
np.random.randn(2)

array([0.03499696, 0.80166057])

In [20]:
np.random.randn(5,5)

array([[-0.86782124, -1.49381953,  0.2469864 ,  0.17837939,  0.26053227],
       [ 1.60893449, -1.39308321, -0.70260945, -1.32895016, -0.74107718],
       [ 0.83587269, -1.01610313, -0.95627429,  0.09230829, -0.66743264],
       [-0.79604983, -1.05325286, -0.00599168,  1.64102404, -0.94971194],
       [ 0.1653874 ,  0.61548861,  0.69108917,  0.05449123, -0.91724456]])

### randint
Retorn valores random desde `low` (inclusive) to `high` (exclusive).

In [21]:
np.random.randint(1,100)

24

In [22]:
np.random.randint(1,100,10)

array([58, 69, 15, 70, 52, 55, 13,  5, 78, 32])

## Array Attributes and Methods


In [23]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr

array([ 2,  3, 22, 19,  4, 46,  8, 32,  2,  9])

## Reshape
La misma data pero en otro shape

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Metodos para encontrar max, min values. O index locations usando argmin or argmax

In [27]:
ranarr

array([ 2,  3, 22, 19,  4, 46,  8, 32,  2,  9])

In [28]:
ranarr.max()

46

In [29]:
ranarr.argmax()

5

In [30]:
ranarr.min()

2

In [31]:
ranarr.argmin()

0

## Shape

Shape es un atributo que tiene un array, no un método

In [32]:
# Vector
arr.shape

(25,)

In [33]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(1,25).shape

(1, 25)

In [35]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [36]:
arr.reshape(25,1).shape

(25, 1)

### dtype

Devuelve el tipo de data (atributo o método?

In [37]:
arr.dtype

dtype('int64')

atributo