# NumPy Indexing and Selection



In [1]:
import numpy as np

In [2]:
#Creating sample array
arr = np.arange(0,11)

In [3]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
Funcionan igual que las listas en este caso pero no en el siguiente.

In [4]:
#Get a value at an iarr
arr[8]

8

In [5]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [6]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting


In [7]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
slice_of_arr[:] =99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

El cambio ocurre en el array original.

In [12]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

La data no es copiada. Las transformaciones suceden en la original. Memoria ;) ok

In [13]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

El formato general es **arr_2d[row][col]** o **arr_2d[row,col]**. recomiendo usar la coma para no confundirse

In [14]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
arr_2d[1:3,0:2]

array([[20, 25],
       [35, 40]])

In [16]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [17]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [18]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [19]:
# Getting individual element value
arr_2d[1,0]

20

In [20]:
arr_2d[0,2]

15

In [21]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [22]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [23]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [24]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Conditional Selection

Este es un concepto muy fundamental que se traducirá directamente a los pandas más adelante!!

Repasemos brevemente cómo usar corchetes para la selección basada en operadores de comparación.

In [25]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr > 4

SyntaxError: invalid syntax (1464412836.py, line 1)

In [27]:
bool_arr = arr>4

In [28]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])